name: Publish Resume
run-name: ${{ github.actor }} is publishing Kedar Panchal's resume
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing to see if this works"
