name: Publish Resume
run-name: ${{ github.actor }} is publishing Kedar Panchal's resume
on: 
  push:
    paths:
      - resume.tex
      - .github/workflows/publish.yaml
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v7
      - run: pdflatex -interaction=nonstopmode resume.tex
      - uses: actions/upload-artifact@v7
        with:
          name: resume-pdf
          path: resume.pdf

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: resume-pdf
      - env:
          GITHUB_TOKEN: ${{ github.token }}
          NAME: ${{ github.sha }}
        run: |
          gh release create "$NAME" resume.pdf --repo "$GITHUB_REPOSITORY" --title "vNAME" 
