name: Render Resume
run-name: ${{ github.actor }} is rendering a resume
on:
  push:
    paths:
      - data.yaml
      - resume.view.yaml
      - .github/workflows/render-resume.yaml
      - src/render/renderer.py
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:debian
    steps:
      - uses: actions/checkout@v7
      - run: mkdir -p dist/resume
      - run: mkdir -p dist/site
      - run: uv run render
      - uses: actions/upload-artifact@v7
        with:
          name: resume-tex
          path: dist/resume/resume.tex

  build:
    runs-on: ubuntu-latest
    needs: render
    container:
      image: texlive/texlive:latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: resume-tex
      - run: pdflatex -interaction=nonstopmode resume.tex
      - uses: actions/upload-artifact@v7
        with:
          name: resume-pdf
          path: resume.pdf

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: resume-pdf
      - env:
          GITHUB_TOKEN: ${{ github.token }}
          SHA: ${{ github.sha }}
        run: |
          NAME="$(date +'%Y.%m.%d')-${SHA:0:6}"
          gh release create "$NAME" resume.pdf --repo "${GITHUB_REPOSITORY}" --title "v$NAME"
